### ISSUE TITLE
Configurar firebase auth

### ISSUE THREAD

**Issue by sudjoao** [Phineas-e-Ferb/jgchat#1]
# Descrição
Conectar aplicativo com o projeto do firebase para que seja possível utilizar o sistema de autenticação;

# Tasks
- [x] Adicionar firebase no projeto;
- [x] Criar o projeto no firebase;
- [x] Adicionar firebase authentication no projeto;
- [x] Criar arquivo de configuração do firebase;
- [x] Criar util para acessar o objeto gerado pelo firebase.
