### ISSUE TITLE
Cadastro de usuário

### ISSUE THREAD

**Issue by sudjoao** [Phineas-e-Ferb/jgchat#2]
# Descrição
Usuário ser capaz de se registrar no aplicativo utilizando um nome, e-mail e senha.

# Tasks
- [x] Criação de tela de registro com form com campos email, nome e senha;
- [x] Criação de metodo que envia dados para firebase;
- [x] Conexão da tela de registro com metódos.
