### ISSUE TITLE
Acessar conta

### ISSUE THREAD

**Issue by sudjoao** [Phineas-e-Ferb/jgchat#3]
# Descrição
Usuário ser capaz de entrar no aplicativo utilizando e-mail e senha cadastrados.

# Tasks
- [x] Criação de tela de login com e-mail e senha;
- [x] Criação de metodo que envia dados para firebase;
- [x] Conexão da tela de login com metódo;
- [ ] Mostrar pop-up de erro caso não dê certo.
