### ISSUE TITLE
Visualizar lista de usuários disponíveis no aplicativo

### ISSUE THREAD

**Issue by sudjoao** [Phineas-e-Ferb/jgchat#4]
# Descrição
Criação de tela com listagem de usuários cadastrados no app para o usuário conversar.

# Tasks
- [x] Criação de tela  com listagem de usuários;
- [x] Criação de metodo que pega lista de usuários no firebase;
- [x] Conexão da lista do firebase com a página.
