### ISSUE TITLE
Enviar mensagens

### ISSUE THREAD

**Issue by sudjoao** [Phineas-e-Ferb/jgchat#5]
# Descrição
Usuário ser capaz de escolher um usuário e enviar uma mensagem para ele

# Tasks
- [x] Criação da tela de conversa com input de mensagem;
- [x] Ao clicar no botão de chat ao lado de um usuário da lista abrir a tela de conversa;
- [x] Criação de metódo que envia uma mensagem para o firebase;
- [x] Conectar metodo com botão de enviar mensagem;
- [ ] Mensagem só deverá aparecer como enviada se o metódo de enviar pro firebase dê certo.
